### ISSUE TITLE
use arsd as package

### ISSUE THREAD

**Issue by WebFreak001** [drug007/nanogui#1]
with submodules you can't depend on this with dub anymore as it doesn't download submodules.

**Comment by drug007** [comment]
this submodule is just temporary solution, when arsd will be released it will be replaced by normal dependency. Current arsd release does not provide needed functionality.

**Comment by drug007** [comment]
I was totally wrong closing the issue.

**Comment by drug007** [comment]
Waiting for [arsd](https://github.com/adamdruppe/arsd) release
