### ISSUE TITLE
Running From Command Line

### ISSUE THREAD

**Issue by FenixFyreX** [drug007/nanogui#10]
OS: Windows 10 64-bit
D Compiler: dmd2 v2.084.1, dub v1.13.0

Using the arsd backend, executing `dub run` in `examples/arsd` in a command line results in a runtime assertion error on line 147 of `arsdbackend.d`. If I open `arsd-example.exe` by double clicking it in the file folder, it works. For some reason, running a nanogui.d app with a terminal already open causes a problem.

**Comment by drug007** [comment]
Unfortunately I have no windows box and can not fix this issue now. I'll do it later.

**Comment by drug007** [comment]
I failed to reproduce it. Could you try it yet another time?
