### ISSUE TITLE
Very laggy on Windows with ArsdBackend

### ISSUE THREAD

**Issue by WebFreak001** [drug007/nanogui#21]
trying to run with ArsdBackend over SdlBackend on Windows results in a very unresponsive window which runs at what feels like 1 frame every 5 seconds

**Comment by drug007** [comment]
In my current developing branch I've dropped `arsd` maintaining due to lack of time. I'm not sure but probably I'll drop `arsd` in master too. If someone is interested in `arsd` it would be better to use original packages by Adam D. Ruppe.

**Comment by drug007** [comment]
Closed because ArsdBackend has been dropped
