### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by aberba** [drug007/nanogui#22]
It depends and an old version of arsd. Can you please update to a never version?

**Comment by drug007** [comment]
currently only arsd v8.0.0 is supported (#24) Is it good enough?

**Comment by aberba** [comment]
@drug007 yes it good enough, thanks. 

I can't get my TextBox to register keyboard inputs as I type. Code is in Gist here (https://gist.github.com/aberba/8b44fa0d57df0551fda24401dca5c205)

When I type the input's text doesn't change. Not sure if its a bug or something I should report.

**Comment by aberba** [comment]
Yeah it was the Arsd backend I switched to SDL after reading #21 and that fixed the issue. You talked about removing Arsd backend from master. I think that's the right thing to do. SDL works just fine.

**Comment by drug007** [comment]
Yes, lacking of time is the reason I can not support Arsd backend anymore. Than I won't merge #24 - it would be better to drop arsd instead of version update.

**Comment by aberba** [comment]
Yes, I agree its better to drop arsd

**Comment by aberba** [comment]
The window has padding in it. Is there a way to remove that padding?

**Comment by drug007** [comment]
> The window has padding in it. Is there a way to remove that padding?

new issue please. Do you mean [nanogui.Window](https://github.com/drug007/nanogui/blob/73b7a1439c254c197392eb456e5b917e0d6f08a6/source/nanogui/window.d#L21) not SDL2 one?
