### ISSUE TITLE
sdl example not building by ldc2

### ISSUE THREAD

**Issue by zkxjzmswkwl** [drug007/nanogui#34]
`../../auxil/source/auxil/modell.d line 958 expression len = getLength() is not a constant`.

Can't be changed to not be `const` because the value's not present at compile time.

Am I missing something?

**Comment by drug007** [comment]
What branch and compiler/compiler version do you use? I just build sdl example successfully using dmd 2.097.2 and `develop` branch.

**Comment by drug007** [comment]
The issue is reproduced with `ldc2` compiler. I'll take a look into it.
