### ISSUE TITLE
Heya. Thanks for this :) but...

### ISSUE THREAD

**Issue by lulcat** [drug007/nanogui#45]
Hey, thank you for this port.. I had it for years but I keep returning to it and there is a obvious bug (here at least), when I resize the
MAIN WINDOW, (resize/maximise) it does NOT update the 'coordinate' system... so when I try to click or move items, the mouse has
to be offset "till you find the correct distance"... This seems like a small bug but not sure why no one notices this? 

Was hoping you would fix this, otherwise it looks great, but ye, if I get a reply I can of course see what this is but still would expect maybe something is wrong in my env? (Doubt it? tried on many different computers over the years :p)

**Comment by drug007** [comment]
Thank you for bug reporting. I use the project for a specific application where this bug has never bothered me. Fixed it in #46

**Comment by lulcat** [comment]
Cheers. Wish I had pointed it out back then :) Until next time Señor droga double-oh-seven.

**Comment by drug007** [comment]
You're welcome!
